import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const deploy = readFileSync(new URL('./deploy.sh', import.meta.url), 'utf8');
const promote = readFileSync(new URL('./promote.sh', import.meta.url), 'utf8');
const rollback = readFileSync(new URL('./rollback.sh', import.meta.url), 'utf8');
const backup = readFileSync(new URL('./backup.sh', import.meta.url), 'utf8');
const restore = readFileSync(new URL('./restore-rehearsal.sh', import.meta.url), 'utf8');
const compose = readFileSync(new URL('./compose.staging.yml', import.meta.url), 'utf8');
const workflow = readFileSync(new URL('../../.github/workflows/deploy.yml', import.meta.url), 'utf8');

assert.match(deploy, /sha256:\[a-f0-9\]\{64\}/);
assert.match(deploy, /mockAiDigest/);
assert.match(deploy, /candidate\.json/);
assert.match(deploy, /up -d --wait --wait-timeout 180/);
assert.match(deploy, /prisma migrate status/);
assert.doesNotMatch(deploy, /manifests\/active\.json/);
assert.match(promote, /manifests\/active\.json/);
assert.match(promote, /\.env\.candidate/);
assert.match(promote, /flock -n 9/);
assert.match(rollback, /MANUAL_DATABASE_COMPATIBILITY_CONFIRMATION/);
assert.match(backup, /--env-file "\$ENV_FILE"/);
assert.match(backup, /MINIO_VOLUME_NAME/);
assert.doesNotMatch(backup, /\|\| true/);
assert.match(backup, /stop backend frontend/);
assert.match(backup, /stop minio minio-proxy/);
assert.match(restore, /COMPOSE_PROJECT_NAME=homefinance-\$RUN_ID/);
assert.doesNotMatch(restore, /dropdb/);
assert.match(restore, /up -d --wait postgres redis minio/);
assert.match(restore, /prisma migrate status/);
assert.match(restore, /minio\/mc/);
assert.match(restore, /mc ls "rehearsal\/\$MINIO_BUCKET"/);
assert.match(restore, /--entrypoint \/bin\/sh/);
assert.match(restore, /-e MINIO_ROOT_USER/);
assert.match(workflow, /Start encrypted browser tunnel/);
assert.match(workflow, /-L 127\.0\.0\.1:4173:127\.0\.0\.1:80/);
assert.match(workflow, /E2E_BASE_URL: http:\/\/127\.0\.0\.1:4173/);
assert.doesNotMatch(workflow, /STAGING_URL/);
assert.match(compose, /minio\/minio:RELEASE\.2025-04-22T22-12-26Z/);
assert.match(compose, /minio-proxy/);
console.log('staging contract PASS');
